ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER ACADEMIA IDENTIFIED BY ACADEMIA;
GRANT CONNECT, RESOURCE, DBA TO ACADEMIA;


DROP TABLE ALUMNOS CASCADE CONSTRAINT;
DROP TABLE PROFESORES CASCADE CONSTRAINT;
DROP TABLE CURSOS CASCADE CONSTRAINT;


 CREATE TABLE ALUMNOS (
 DNI NUMBER(10),
 NOMBRE VARCHAR2(20),
 APELLIDO1 VARCHAR2(20),
 APELLIDO2 VARCHAR2(20),
 SEXO VARCHAR2(2),
 FECHA_NACIMIENTO DATE,
 CURSO VARCHAR2(10),
 
 CONSTRAINT PK_ALU PRIMARY KEY (DNI),
 CONSTRAINT CHK_ALU CHECK (SEXO IN('H', 'M'))
 );
 
CREATE TABLE PROFESORES (
DNI NUMBER(10),
NOMBRE VARCHAR2(20),
APELLIDO1 VARCHAR2(20),
APELLIDO2 VARCHAR2(20),
DIRECCION VARCHAR2(30),
TITULO VARCHAR2(20),
GANA NUMBER(5),

CONSTRAINT PK_PROF PRIMARY KEY (DNI)
);

CREATE TABLE CURSOS(
COD_CURSO NUMBER(10),
NOMBRE_CURSO VARCHAR2(30),
DNI_PROFESOR NUMBER(10),
MAX_ALUMNOS NUMBER(2),
FECHA_INICIO DATE,
FECHA_FIN DATE,
NUM_HORAS NUMBER(3),

CONSTRAINT PK_CURSO PRIMARY KEY (COD_CURSO),
CONSTRAINT FK_CURSO FOREIGN KEY (DNI_PROFESOR) REFERENCES PROFESORES(DNI)
);

--2.
INSERT INTO PROFESORES VALUES (32432455, 'Juan', 'Arch', 'López', 'Puerta Negra, 4', 'Ing. Informática', 7500);	
INSERT INTO PROFESORES VALUES (43215643, 'María', 'Oliva', 'Rubio', 'Juan Alfonso 32', 'Lda. Fil. Inglesa', 5400);
--3.
INSERT INTO CURSOS 
VALUES (1, 'Inglés Básico', 43215643, 15, TO_DATE('01/11/00', 'DD/MM/YY'), TO_DATE('22-DEC-00', 'DD-MONTH-YY'), 120);
INSERT INTO CURSOS (COD_CURSO, NOMBRE_CURSO, DNI_PROFESOR, FECHA_INICIO, NUM_HORAS) 
VALUES (2, 'Administración Linux', 32432455, TO_DATE('01-SEP-00', 'DD/MONTH/YY'), 80);
--4.





























