ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER FUTBOL IDENTIFIED BY FUTBOL;
GRANT CONNECT, RESOURCE, DBA TO FUTBOL;

CREATE TABLE EQUIPOS
(
COD_EQUIPO VARCHAR2(10),
NOMBRE VARCHAR2(30) NOT NULL,
LOCALIDAD VARCHAR2(15),

CONSTRAINT PK_EQU PRIMARY KEY (COD_EQUIPO)
);

CREATE TABLE JUGADORES
(
COD_JUGADOR VARCHAR2(4),
NOMBRE VARCHAR2(30) NOT NULL,
FECHA_NAC DATE,
DEMARCACION VARCHAR2(10),
COD_EQUIPO VARCHAR2(4) NOT NULL,

CONSTRAINT PK_JUG PRIMARY KEY (COD_JUGADOR),
CONSTRAINT FK_JUG FOREIGN KEY (COD_EQUIPO) REFERENCES EQUIPOS(COD_EQUIPO)
);

CREATE TABLE PARTIDOS 
(
COD_PARTIDO VARCHAR2(4),
COD_EQU_LOCAL VARCHAR2(4) NOT NULL,
COD_EQU_VISIT VARCHAR2(4) NOT NULL,
FECHA DATE,
COMPETICION VARCHAR2(4),
JORNADA VARCHAR2(20),

CONSTRAINT PK_PART PRIMARY KEY (COD_PARTIDO),
CONSTRAINT FK_PART FOREIGN KEY (COD_EQU_LOCAL) REFERENCES EQUIPOS(COD_EQUIPO),
CONSTRAINT FK2_PART FOREIGN KEY (COD_EQU_VISIT) REFERENCES EQUIPOS(COD_EQUIPO),
CONSTRAINT CHK_PART CHECK ((EXTRACT(MONTH FROM FECHA))!=7 OR (EXTRACT(MONTH FROM FECHA))!=8),
CONSTRAINT CHK_PART2 CHECK (COMPETICION IN('Copa', 'Liga'))
);


CREATE TABLE INCIDENCIAS
(
NUM_INCIDENCIA VARCHAR2(6),
COD_PARTIDO VARCHAR2(4) NOT NULL,
COD_JUGADOR VARCHAR2(4) NOT NULL,
MINUTO NUMBER(2),
TIPO VARCHAR2(20),

CONSTRAINT PK_IND PRIMARY KEY (NUM_INCIDENCIA),
CONSTRAINT FK_IND FOREIGN KEY (COD_PARTIDO) REFERENCES PARTIDOS(COD_PARTIDO),
CONSTRAINT FK1_IND FOREIGN KEY (COD_JUGADOR) REFERENCES JUGADORES(COD_JUGADOR),
CONSTRAINT CHK_IND CHECK (MINUTO BETWEEN 1 AND 99)
);

ALTER TABLE JUGADORES ADD CONSTRAINT CHK_JUG CHECK (regexp_like(NOMBRE,'^[A-Z|{1}$'));
ALTER TABLE JUGADORES ADD CONSTRAINT CHK2_JUG CHECK (DEMARCACION IN('Portero', 'Defensa', 'Medio', 'Delantero'));
ALTER TABLE EQUIPOS ADD CONSTRAINT CHK3_JUG CHECK (regexp_like(COD_EQUIPO, '[0-9]{1}$'));
ALTER TABLE INCIDENCIAS ADD CONSTRAINT CHK4_TIP CHECK ((TIPO)IS NULL);
ALTER TABLE EQUIPOS ADD GOLES_MARCADOS NUMBER(3);


----------------------------------------------------------------------------------------------------------------





