ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER JARDINERIA IDENTIFIED BY JARDINERIA;
GRANT CONNECT, RESOURCE, DBA TO JARDINERIA;


CREATE TABLE GAMA_PRODUCTO
(
GAMA VARCHAR2(50),
DESCRIP_TEXT VARCHAR2(100),
DESCRIP_HTML VARCHAR2(100),
IMAGEN VARCHAR2(256),

CONSTRAINT PK_GP PRIMARY KEY (GAMA)
);

CREATE TABLE PRODUCTO 
(
CODIGO_PRODUCTO VARCHAR2(15),
NOMBRE VARCHAR2(70) NOT NULL,
GAMA VARCHAR2(50) NOT NULL,
DIMENSIONES VARCHAR2(25),
PROVEEDOR VARCHAR2(50),
DESCRIPCION VARCHAR2(100),
CANT_STOCK NUMBER(6) NOT NULL,
PRECIO_VENTA NUMBER(15,2) NOT NULL,
PRECIO_PROVEEDOR NUMBER(15,2),

CONSTRAINT PK_PROD PRIMARY KEY (CODIGO_PRODUCTO),
CONSTRAINT FK_PROD FOREIGN KEY (GAMA) REFERENCES GAMA_PRODUCTO(GAMA)
);

CREATE TABLE OFICINA 
(
CODIGO_OFICINA VARCHAR2(10),
CIUDAD VARCHAR2(30) NOT NULL,
PAIS VARCHAR2(50) NOT NULL,
REGION VARCHAR2(50),
CODIGO_POSTAL VARCHAR2(10) NOT NULL,
TELEFONO VARCHAR2(20) NOT NULL,
LINEA_DIR_1 VARCHAR2(50) NOT NULL,
LINEA_DIR_2 VARCHAR2(50),

CONSTRAINT PK_OFI PRIMARY KEY (CODIGO_OFICINA)
);

CREATE TABLE EMPLEADO 
(
CODIGO_EMPLEADO NUMBER(11),
NOMBRE VARCHAR2(50) NOT NULL,
APELLIDO1 VARCHAR2(50) NOT NULL,
APELLIDO2 VARCHAR2(50),
EXTENSION VARCHAR2(10) NOT NULL,
EMAIL VARCHAR2(100) NOT NULL,
CODIGO_OFICINA VARCHAR2(10) NOT NULL,
CODIGO_JEFE NUMBER(11),
PUESTO VARCHAR2(50),

CONSTRAINT PK_EMPLE PRIMARY KEY (CODIGO_EMPLEADO),
CONSTRAINT FK_EMPLE FOREIGN KEY (CODIGO_OFICINA) REFERENCES OFICINA(CODIGO_OFICINA),
CONSTRAINT FK2_EMPLE FOREIGN KEY (CODIGO_JEFE) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE CLIENTE 
(
CODIGO_CLIENTE NUMBER(11),
NOMBRE_CLI VARCHAR2(50) NOT NULL,
NOMBRE_CONTAC VARCHAR2(30),
APELLIDO_CONTAC VARCHAR2(30),
TLFN NUMBER(15) NOT NULL,
FAX VARCHAR2(15) NOT NULL,
LINEA_DIREC_1 VARCHAR2(50) NOT NULL,
CIUDAD VARCHAR2(50) NOT NULL,
REGION VARCHAR2(50),
PAIS VARCHAR2(50),
CODIGO_PNT PK_CLI PRIMARY KEY (CODIGO_CLIENTE),
CONSTRAIOSTAL VARCHAR2(10),
COD_EMP_REP_VENT NUMBER(11),
LIMITE_CREDITO NUMBER(15,2),

CONSTRAINT FK_CLI FOREIGN KEY (COD_EMP_REP_VENT) REFERENCES EMPLEADO(CODIGO_EMPLEADO)
);

CREATE TABLE PAGO
(
CODIGO_CLIENTE NUMBER(11) NOT NULL,
FORMA_PAGO VARCHAR2(40) NOT NULL,
ID_TRANSACCION VARCHAR2(50),
FECHA_PAGO DATE,
TOTAL DECIMAL(15,2),

CONSTRAINT PK_PAGO PRIMARY KEY (CODIGO_CLIENTE, ID_TRANSACCION),
CONSTRAINT FK_PAG FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);

CREATE TABLE PEDIDO 
(
CODIGO_PEDIDO NUMBER(11),
FECHA_PEDIDO DATE NOT NULL,
FECHA_ESPERADA DATE NOT NULL,
FECHA_ENTREGA DATE,
ESTADO VARCHAR2(15) NOT NULL,
COMENTARIOS VARCHAR2(150),
CODIGO_CLIENTE NUMBER(11) NOT NULL,

CONSTRAINT PK_PED PRIMARY KEY (CODIGO_PEDIDO),
CONSTRAINT FK_PED FOREIGN KEY (CODIGO_CLIENTE) REFERENCES CLIENTE(CODIGO_CLIENTE)
);


CREATE TABLE DETALLE_PEDIDO
(
CODIGO_PEDIDO NUMBER(11),
CODIGO_PRODUCTO VARCHAR2(15),
CANTIDAD NUMBER(11) NOT NULL,
PRECIO_UNIDAD DECIMAL(15,2) NOT NULL,
NUMERO_LINEA NUMBER(6) NOT NULL,

CONSTRAINT PK_DET_PED PRIMARY KEY (CODIGO_PEDIDO, CODIGO_PRODUCTO),
CONSTRAINT FK_DET_PED FOREIGN KEY (CODIGO_PEDIDO) REFERENCES PEDIDO(CODIGO_PEDIDO),
CONSTRAINT FK2_DET_DEP FOREIGN KEY (CODIGO_PRODUCTO) REFERENCES PRODUCTO(CODIGO_PRODUCTO)
);


























