--ALTER SESSION SET "_oracle_script"=TRUE;
--CREATE USER TALLER IDENTIFIED BY TALLER;
--GRANT CONNECT, RESOURCE, DBA TO TALLER;


/*
 * DROP TABLE CLIENTES CASCADE CONSTRAINT;
DROP TABLE MARCAS CASCADE CONSTRAINT;
DROP TABLE VENTAS CASCADE CONSTRAINT;
DROP TABLE COCHES CASCADE CONSTRAINT;
DROP TABLE CONCESIONARIO CASCADE CONSTRAINT;
DROP TABLE DISTRIBUCION CASCADE CONSTRAINT;
 */


CREATE TABLE CLIENTES 
(
DNI VARCHAR2(10),
NOMBRE VARCHAR2(20),
APELLIDOS VARCHAR2(20),
CIUDAD VARCHAR2(30),

CONSTRAINT PK_CLI PRIMARY KEY (DNI)
);

CREATE TABLE CONCESIONARIO 
(
CIFC VARCHAR2(10),
NOMBRE VARCHAR2(10),
CIUDAD VARCHAR2(30),
CIFCMATRIZ VARCHAR2(10),

CONSTRAINT PK_CON PRIMARY KEY (CIFC),
CONSTRAINT FK2_CON FOREIGN KEY (CIFCMATRIZ) REFERENCES CONCESIONARIO(CIFC)
);

CREATE TABLE MARCAS
(
COD_MARCA NUMBER(5),
NOMBRE VARCHAR2(20),
PAIS VARCHAR2(20),

CONSTRAINT PK_MAR PRIMARY KEY (COD_MARCA)
);

CREATE TABLE COCHES 
(
COD_COCHE NUMBER(5),
COD_MARCA NUMBER(5),
MODELO VARCHAR2(10),
MATRICULA VARCHAR2(8),
COLOR VARCHAR2(10),

CONSTRAINT PK_COCHES PRIMARY KEY (COD_COCHE),
CONSTRAINT FK_COCHES FOREIGN KEY (COD_MARCA) REFERENCES MARCAS(COD_MARCA)
);

CREATE TABLE VENTAS 
(
COD_COCHE NUMBER(5),
CIFC VARCHAR2(10),
DNI VARCHAR2(10),
FECHA_VENTA DATE,
PVP NUMBER(5),

CONSTRAINT PK_VEN PRIMARY KEY (COD_COCHE),
CONSTRAINT FK_VEN FOREIGN KEY (COD_COCHE) REFERENCES COCHES(COD_COCHE),
CONSTRAINT FK2_VEN FOREIGN KEY (DNI) REFERENCES CLIENTES(DNI),
CONSTRAINT FK3_VEN FOREIGN KEY (CIFC) REFERENCES CONCESIONARIO(CIFC)
);

CREATE TABLE DISTRIBUCION 
(
CIFC VARCHAR2(10),
COD_COCHE NUMBER(5),
FECHA DATE,

CONSTRAINT PK_DIS PRIMARY KEY (CIFC, COD_COCHE),
CONSTRAINT FK_DIS FOREIGN KEY (CIFC) REFERENCES CONCESIONARIO(CIFC),
CONSTRAINT FK2_DIS FOREIGN KEY (COD_COCHE) REFERENCES COCHES(COD_COCHE)
);

------------------------------------------------------------------------------

--1.

ALTER TABLE VENTAS MODIFY FECHA_VENTA DATE DEFAULT SYSDATE;


--2.

ALTER TABLE COCHES ADD CONSTRAINT CHK_COCHCES CHECK (UPPER(COLOR)=COLOR);
ALTER TABLE COCHES ADD CONSTRAINT CHK2_COCHES CHECK (COLOR IN ('ROJO', 'AMARILLO', 'VERDE'));


--3.

ALTER TABLE CLIENTES ADD CONSTRAINT CHK_CLI CHECK (UPPER(CIUDAD)=CIUDAD);
ALTER TABLE CONCESIONARIO ADD CONSTRAINT CHK_CON CHECK (UPPER(CIUDAD)=CIUDAD);


--4.

ALTER TABLE DISTRIBUCION ADD AREA VARCHAR2(10);

--5.

ALTER TABLE DISTRIBUCION ADD CONSTRAINT CHK_DIS CHECK (AREA LIKE '%T%');

--6.

ALTER TABLE CONCESIONARIO DISABLE CONSTRAINT FK2_CON;


--7.

ALTER TABLE CONCESIONARIO DROP CONSTRAINT FK2_CON;










