ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER TIENDA IDENTIFIED BY TIENDA;
GRANT CONNECT, RESOURCE, DBA TO TIENDA;

DROP TABLE FABRICANTE CASCADE CONSTRAINT;
DROP TABLE PRODUCTO CASCADE CONSTRAINT;

CREATE TABLE FABRICANTE (
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),

CONSTRAINT PK_FABRI PRIMARY KEY (CODIGO)
);

CREATE TABLE PRODUCTO (
CODIGO NUMBER(10),
NOMBRE VARCHAR2(100),
PRECIO FLOAT(10),
CODIGO_FABRICANTE NUMBER(10),

CONSTRAINT PK_PRODUCTO PRIMARY KEY (CODIGO),
CONSTRAINT FK_PRODUCTO FOREIGN KEY (CODIGO_FABRICANTE) REFERENCES FABRICANTE(CODIGO) ON DELETE CASCADE
);

SELECT * FROM FABRICANTE;
SELECT * FROM PRODUCTO;

--TABLA FABRICANTE
INSERT INTO FABRICANTE VALUES(1, 'ASUS');
INSERT INTO FABRICANTE VALUES(2, 'LENOVO');
INSERT INTO FABRICANTE VALUES(3, 'HEWLETT-PACKARD');
INSERT INTO FABRICANTE VALUES(4, 'SAMSUNG');
INSERT INTO FABRICANTE VALUES(5, 'SEAGATE');
INSERT INTO FABRICANTE VALUES(6, 'CRUCIAL');
INSERT INTO FABRICANTE VALUES(7, 'GIGABYTE');
INSERT INTO FABRICANTE VALUES(8, 'HUAWEI');
INSERT INTO FABRICANTE VALUES(9, 'XIAOMI');

--TABLA PRODUCTO
INSERT INTO PRODUCTO VALUES(1, 'Disco duro SATA3 1TB', 86.99, 5);
INSERT INTO PRODUCTO VALUES(2, 'Memoria RAM DDR4 8GB', 120, 6);
INSERT INTO PRODUCTO VALUES(3, 'Disco SSD 1 TB', 150.99, 4);
INSERT INTO PRODUCTO VALUES(4, 'GeForce GTX 1050Ti', 185, 7);
INSERT INTO PRODUCTO VALUES(5, 'GeForce GTX 1080 Xtreme', 755, 6);
INSERT INTO PRODUCTO VALUES(6, 'Monitor 24 LED Full HD', 202, 1);
INSERT INTO PRODUCTO VALUES(7, 'Monitor 27 LED Full HD', 245.99, 1);
INSERT INTO PRODUCTO VALUES(8, 'Portátil Yoga 520', 559, 2);
INSERT INTO PRODUCTO VALUES(9, 'Portátil Ideapd 320', 444, 5);
INSERT INTO PRODUCTO VALUES(10, 'Impresora HP Deskjet 3720', 59.99, 3);
INSERT INTO PRODUCTO VALUES(11, 'Impresora HP Laserjet Pro M26nw', 180, 3);

--RESTRICCIONES
--1. Inserta un nuevo fabricante indicando su código y su nombre.
INSERT INTO FABRICANTE VALUES (10, 'IPHONE');
--2. Inserta un nuevo fabricante indicando solamente su nombre.
ALTER TABLE PRODUCTO DISABLE CONSTRAINT FK_PRODUCTO;
ALTER TABLE FABRICANTE DISABLE CONSTRAINT PK_FABRI;
INSERT INTO FABRICANTE (NOMBRE) VALUES('XIAOMI');
--ALTER TABLE FABRICANTE ENABLE CONSTRAINT PK_FABRI;
--ALTER TABLE PRODUCTO ENABLE CONSTRAINT FK_PRODUCTO;
--3. Inserta un nuevo producto asociado a uno de los nuevos fabricantes. La
--   sentencia de inserción debe incluir: código , nombre , precio y código_fabricante 
INSERT INTO PRODUCTO VALUES (12, 'M1 Chip', 799.99, 10);
--4. Inserta un nuevo producto asociado a uno de los nuevos fabricantes. La
--   sentencia de inserción debe incluir: nombre , precio y código_fabricante 
ALTER TABLE PRODUCTO DISABLE CONSTRAINT PK_PRODUCTO;
INSERT INTO PRODUCTO (NOMBRE, PRECIO, CODIGO_FABRICANTE) VALUES ('Lenovo C24-25 23.8" WLED FullHD FreeSynC', 106.99, 2);
--5. Elimina el fabricante Asus . ¿Es posible eliminarlo? Si no fuese posible,
--   ¿qué cambios debería realizar para que fuese posible borrarlo?
DELETE FROM FABRICANTE WHERE NOMBRE='ASUS';--NO VÁLIDO
--DEBES DESHABILITAR EL CODIGO PARA PODER AÑADIR EL NOMBRE SIN PROBLEMA DE DEJAR UN VALOR
--PK EN NULO.
--6. Elimina el fabricante Xiaomi . ¿Es posible eliminarlo? Si no fuese posible,
--¿qué cambios debería realizar para que fuese posible borrarlo?
DELETE FROM FABRICANTE WHERE NOMBRE='XIAOMI';--NO VÁLIDO
--DEBES DESHABILITAR EL CODIGO PARA PODER AÑADIR EL NOMBRE SIN PROBLEMA DE DEJAR UN VALOR
--PK EN NULO.
--7. Actualiza el código del fabricante Lenovo y asígnale el valor 20. ¿Es
--posible actualizarlo? Si no fuese posible, ¿qué cambios debería realizar
--para que fuese actualizarlo?
--ALTER TABLE PRODUCTO DISABLE CONSTRAINT FK_PRODUCTO;
--ALTER TABLE FABRICANTE DISABLE CONSTRAINT PK_FABRI;
--DEBERIAS EJECUTAR ESAS DOS SENTENCIAS EN LAS CUALES DESAHILITAS LA PK Y LA FK DEPENDIENTE DE OTRA TABLA,
--PARA PODER CAMBIAR ESE VALOR.
UPDATE FABRICANTE SET CODIGO = 20 WHERE CODIGO = 2;
--8. Actualiza el código del fabricante Huawei y asígnale el valor 30. ¿Es
--posible actualizarlo? Si no fuese posible, ¿qué cambios debería realizar
--para que fuese actualizarlo?
--ALTER TABLE PRODUCTO DISABLE CONSTRAINT FK_PRODUCTO;
--ALTER TABLE FABRICANTE DISABLE CONSTRAINT PK_FABRI;
--DEBERIAS EJECUTAR ESAS DOS SENTENCIAS EN LAS CUALES DESAHILITAS LA PK Y LA FK DEPENDIENTE DE OTRA TABLA,
--PARA PODER CAMBIAR ESE VALOR.
UPDATE FABRICANTE SET CODIGO = 30 WHERE CODIGO = 8;
--9. Actualiza el precio de todos los productos sumándole 5 € al precio
--actual.
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 1;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 2;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 3;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 4;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 5;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 6;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 7;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 8;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 9;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 10;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO = 11;
UPDATE PRODUCTO SET PRECIO = ROUND(PRECIO+5) WHERE CODIGO_FABRICANTE = 2;

--10. Elimina todas las impresoras que tienen un precio menor de 200 €

--SELECT * FROM PRODUCTO WHERE NOMBRE LIKE '%Impresora%' AND PRECIO < 200;
DELETE FROM PRODUCTO WHERE NOMBRE LIKE '%Impresora%' AND PRECIO < 200;





