ALTER SESSION SET "_oracle_script"=TRUE;
CREATE USER SHOP IDENTIFIED BY SHOP;
GRANT CONNECT, RESOURCE, DBA TO SHOP;

CREATE TABLE FABRICANTES 
(
COD_FABRICANTE NUMBER(3),
NOMBRE VARCHAR2(15),
PAIS VARCAHR2(15),

CONSTRAINT PK_FABRI PRIMARY KEY (COD_FABRICANTE)
);

CREATE TABLE ARTICULOS 
(
ARTICULO VARCHAR2(20),
COD_FABRICANTE NUMBER(3),
PESO NUMBER(3),
CATEGORIA VARCHAR2(10),
PRECIO_VENTA NUMBER(4,2),
PRECIO_COSTO NUMBER(4,2),
EXISTENCIAS NUMBER(5),

CONSTRAINT PK_ART PRIMARY KEY (ARTICULO, COD_FABRICANTE, PESO, CATEGORIA),
CONSTRAINT FK_ART FOREIGN KEY (COD_FABRICANTE) REFERENCES FABRICANTES(COD_FABRICANTE),

);